"""The terminal brand follows the website: logo drawings, colours and readability.

`src/polaris/check/brand_site.py` is generated by `scripts/brand_from_site.py` from the website's
brand files. These tests redraw the logo from the paths stored in it, check that every colour
used for text stays readable, and, with POLARIS_SITE_DIR pointing at a checkout of the website,
that nothing has drifted from the site.
"""

from __future__ import annotations

import importlib.util
import os
from pathlib import Path
from types import ModuleType

import pytest

from polaris.check import brand
from polaris.check import brand_site as site

ROOT = Path(__file__).resolve().parents[1]
BLOCKS = set(" \u2580\u2584\u2588\u258c\u2590\u2596\u2597\u2598\u2599\u259a\u259b\u259c\u259d\u259e\u259f")
TEXT_ROLES = ("heading", "text", "muted", "accent", "star", "fix_now", "check_this", "worth_a_look", "clear",
              "code", "code.number")


def generator() -> ModuleType:
    spec = importlib.util.spec_from_file_location("brand_from_site", ROOT / "scripts" / "brand_from_site.py")
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_drawings_are_the_site_logo() -> None:
    script = generator()
    paths = {"symbol": (site.STAR_PATH, site.STAR_VIEWBOX), "wordmark": (site.WORDMARK_PATH, site.WORDMARK_VIEWBOX)}
    assert site.DRAWINGS == script.DRAWINGS
    for name, logo, columns, rows, threshold in site.DRAWINGS:
        art = getattr(site, name)
        assert art == script.draw(*paths[logo], columns, rows, threshold), f"{name} was edited by hand"
        assert 0 < len(art) <= rows and all(len(row) <= columns and set(row) <= BLOCKS for row in art)
        assert art[0].strip() and art[-1].strip()


def test_lockups_follow_the_site_proportions() -> None:
    # In the site's header the star is about 1.4 times as tall as the wordmark beside it.
    for star, wordmark in ((site.STAR_LARGE, site.WORDMARK_LARGE), (site.STAR_SMALL, site.WORDMARK_SMALL)):
        assert 1.2 <= len(star) / len(wordmark) <= 1.6


@pytest.mark.parametrize("palette", ["dark", "light"])
def test_text_colours_are_readable(palette: str) -> None:
    colours = brand.PALETTES[palette]
    for role in TEXT_ROLES:
        for background in ("background", "surface"):
            assert brand.contrast(colours[role], colours[background]) >= 4.5, (role, background)
    assert brand.contrast(colours["selected.text"], colours["selected"]) >= 4.5
    assert brand.contrast(colours["selected.muted"], colours["selected"]) >= 4.5
    for stop in brand.WORDMARK_GRADIENTS[palette]:
        assert brand.contrast(stop, colours["background"]) >= 4.5, stop
    for glow in brand.STAR_GLOWS[palette]:
        assert brand.contrast(glow, colours["background"]) >= 3, glow


def test_colours_come_from_the_site() -> None:
    known = {*site.LIGHT.values(), *site.DARK.values(), *site.CODE.values(), site.STAR_GOLD}
    for palette in ("dark", "light"):
        assert set(brand.PALETTES[palette].values()) <= known
        assert set(brand.WORDMARK_GRADIENTS[palette]) <= known
        assert set(brand.STAR_GLOWS[palette]) <= known
    assert brand.PALETTES["dark"]["background"] == site.DARK["carbon"] == "#142f27"
    assert brand.PALETTES["dark"]["star"] == site.STAR_GOLD == "#d7b75d"
    assert brand.COMPACT == "\u2736 POLARIS"


@pytest.mark.skipif(not os.environ.get("POLARIS_SITE_DIR"), reason="set POLARIS_SITE_DIR to a website checkout")
def test_the_brand_matches_the_website() -> None:
    assert generator().main(["--site", os.environ["POLARIS_SITE_DIR"], "--check"]) == 0
