"""Warp custom themes that match the Polaris website: Polaris North (dark) and Polaris Paper (light).

`polaris setup warp --theme` installs them into Warp's themes folder (Warp docs: Custom Themes).
Every colour comes from the site's own tokens in `polaris.check.brand_site`: North is the site's
forest-green code windows with the logo's gold, Paper its porcelain pages. The YAML is written by
hand (no YAML library) and starts with `THEME_MARKER`, so setup can tell its own files from a
theme someone else wrote. Warp's settings are never touched; the user picks the theme in Warp.
"""

from __future__ import annotations

import os
import re
import sys
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path

THEME_MARKER = "# Polaris theme: generated by polaris setup; matches polaris.theovex.com"
ANSI = ("black", "red", "green", "yellow", "blue", "magenta", "cyan", "white")
HEX_COLOUR = re.compile(r"#[0-9a-f]{6}")
PICK_THEME = (
    "Pick Polaris North (dark) or Polaris Paper (light) in Warp: Settings > Appearance > Themes. Warp may take a "
    "minute to notice new themes; restarting Warp shows them right away. For the full Polaris look, set the font "
    "to IBM Plex Mono in Settings > Appearance > Text (free download)."
)


@dataclass(frozen=True)
class WarpTheme:
    """One Warp custom theme. A pair of colours is a gradient: (left, right) for the accent,
    (top, bottom) for the background. `normal` and `bright` follow the ANSI order in `ANSI`."""

    file: str
    name: str
    about: str
    details: str  # Warp's word for the theme's kind: "darker" (dark) or "lighter" (light)
    accent: str | tuple[str, str]
    cursor: str
    background: str | tuple[str, str]
    foreground: str
    normal: tuple[str, ...]
    bright: tuple[str, ...]


def mix(first: str, second: str, amount: float) -> str:
    """Blend two `#rrggbb` colours channel by channel: 0 gives `first`, 1 gives `second`."""
    pairs = ((int(first[index:index + 2], 16), int(second[index:index + 2], 16)) for index in (1, 3, 5))
    return "#" + "".join(f"{round(low + (high - low) * amount):02x}" for low, high in pairs)


def warp_themes() -> tuple[WarpTheme, WarpTheme]:
    """Polaris North and Polaris Paper, from the website's colour tokens."""
    from polaris.check import brand_site as site

    dark, light, code, gold = site.DARK, site.LIGHT, site.CODE, site.STAR_GOLD
    north = WarpTheme(
        file="polaris_north.yaml", name="Polaris North", details="darker",
        about="The Polaris website's forest-green code windows, with the logo's gold star.",
        accent=(dark["violet"], gold), cursor=gold, background=(dark["navy-1"], dark["carbon"]),
        foreground=dark["cloud"],
        normal=(dark["navy-2"], dark["flag"], dark["ok"], gold, mix(light["blue"], light["paper"], 0.55),
                mix(light["pink"], light["paper"], 0.5), code["string"], dark["smoke"]),
        bright=(dark["graphite"], mix(dark["flag"], dark["ink"], 0.4), dark["violet"], code["function"],
                mix(light["blue"], light["paper"], 0.7), dark["context"], code["type"], dark["ink"]),
    )
    paper = WarpTheme(
        file="polaris_paper.yaml", name="Polaris Paper", details="lighter",
        about="The Polaris website's porcelain pages, in its forest green and brass.",
        accent=(light["violet"], light["pink"]), cursor=light["violet"], background=light["paper"],
        foreground=light["ink"],
        normal=(light["ink"], light["flag"], light["ok"], light["context"], light["blue"], light["pink"],
                light["violet"], light["navy-3"]),
        bright=(light["steel"], mix(light["flag"], light["ink"], 0.25), mix(light["ok"], light["ink"], 0.3),
                mix(light["context"], light["ink"], 0.25), mix(light["blue"], light["ink"], 0.3),
                mix(light["pink"], light["ink"], 0.3), mix(light["violet"], light["ink"], 0.3), light["navy-2"]),
    )
    return north, paper


def theme_yaml(theme: WarpTheme) -> str:
    """The theme file in Warp's custom theme format. Every colour is a quoted `#rrggbb`."""

    def colour(value: str) -> str:
        if not HEX_COLOUR.fullmatch(value):
            raise ValueError("theme colours must be lowercase #rrggbb")
        return f"'{value}'"

    def setting(key: str, value: str | tuple[str, str], ends: tuple[str, str]) -> list[str]:
        if isinstance(value, str):
            return [f"{key}: {colour(value)}"]
        return [f"{key}:", f"  {ends[0]}: {colour(value[0])}", f"  {ends[1]}: {colour(value[1])}"]

    lines = [
        THEME_MARKER,
        f"# {theme.about} Pick it in Warp: Settings > Appearance > Themes.",
        f"name: {theme.name}",
        *setting("accent", theme.accent, ("left", "right")),
        f"cursor: {colour(theme.cursor)}",
        *setting("background", theme.background, ("top", "bottom")),
        f"foreground: {colour(theme.foreground)}",
        f"details: {theme.details}",
        "terminal_colors:",
    ]
    for group, values in (("normal", theme.normal), ("bright", theme.bright)):
        lines.append(f"  {group}:")
        lines += [f"    {name}: {colour(value)}" for name, value in zip(ANSI, values, strict=True)]
    return "\n".join(lines) + "\n"


def warp_themes_folder(home: Path, *, platform: str = sys.platform,
                       environ: Mapping[str, str] = os.environ) -> Path:
    """Where Warp looks for custom themes on this system (Warp docs: Custom Themes)."""
    if platform == "darwin":
        return home / ".warp" / "themes"
    if platform == "win32":
        appdata = environ.get("APPDATA", "")
        base = Path(appdata) if appdata and Path(appdata).is_absolute() else home / "AppData" / "Roaming"
        return base / "warp" / "Warp" / "data" / "themes"
    data = environ.get("XDG_DATA_HOME", "")
    base = Path(data) if data and Path(data).is_absolute() else home / ".local" / "share"
    return base / "warp-terminal" / "themes"
