"""GENERATED by scripts/brand_from_site.py from the Polaris website. Do not edit by hand.

The star and the POLARIS wordmark (the site's public/brand SVG files), drawn with quadrant
blocks, and the site's colour tokens: LIGHT for its porcelain pages (src/app/globals.css),
DARK for its forest-green code windows (.dark-surface in src/styles/experience.css), CODE
for its polaris-north code colours (src/lib/highlight.ts), STAR_GOLD for the logo's gold.
"""

from __future__ import annotations

STAR_PATH = 'M55.00 47.00 L50.00 8.00 L64.00 0.00 L65.00 47.00 L60.00 52.00Z M68.76 49.17 L89.64 31.34 L103.57 39.46 L73.76 57.83 L66.93 56.00Z M73.76 62.17 L99.64 71.34 L99.57 87.46 L68.76 70.83 L66.93 64.00Z M65.00 73.00 L70.00 100.00 L56.00 108.00 L55.00 73.00 L60.00 68.00Z M51.24 70.83 L30.36 88.66 L16.43 80.54 L46.24 62.17 L53.07 64.00Z M46.24 57.83 L20.36 48.66 L20.43 32.54 L51.24 49.17 L53.07 56.00Z'
STAR_VIEWBOX = (120.0, 120.0)
WORDMARK_PATH = 'M0 29V1H13C19.5 1 23 4.6 23 10C23 15.4 19.5 19 13 19H4.6V29ZM4.6 5.2V14.8H12.8C16.5 14.8 18.4 13.1 18.4 10C18.4 6.9 16.5 5.2 12.8 5.2Z M41.5 0C50 0 55.5 5.7 55.5 15C55.5 24.3 50 30 41.5 30C33 30 27.5 24.3 27.5 15C27.5 5.7 33 0 41.5 0ZM41.5 4.3C35.8 4.3 32.2 8.2 32.2 15C32.2 21.8 35.8 25.7 41.5 25.7C47.2 25.7 50.8 21.8 50.8 15C50.8 8.2 47.2 4.3 41.5 4.3Z M62 1H66.6V24.7H83.5L79.2 29H62Z M85 29L96.1 1H101.1L112.2 29H107.2L104.6 22H92.4L89.8 29ZM94 17.8H103L98.5 5.8Z M118 29V1H131C137.6 1 141 4.5 141 9.8C141 13.8 139 16.7 135.4 18L142.5 29H137L130.7 18.7H122.6V29ZM122.6 5.2V14.6H130.8C134.6 14.6 136.4 13 136.4 9.9C136.4 6.8 134.6 5.2 130.8 5.2Z M149 1H153.6V29H149Z M162 21.1H166.7C167.2 24.3 170.1 26 174.3 26C178.5 26 181.4 24.3 181.4 21.7C181.4 18.9 178.7 18.2 173.9 17.1C167.7 15.7 162.8 14.3 162.8 8.6C162.8 3.4 167.3 0 173.9 0C180.8 0 185.3 3.5 185.8 8.9H181.1C180.5 5.8 177.9 4 173.8 4C169.9 4 167.4 5.6 167.4 8.1C167.4 10.9 170.2 11.6 175 12.7C181.2 14.1 186.1 15.6 186.1 21.2C186.1 26.6 181.4 30 174.3 30C167.1 30 162.3 26.6 162 21.1Z'
WORDMARK_VIEWBOX = (196.0, 30.0)
STAR_GOLD = '#d7b75d'

# (name, logo, columns, rows, threshold) of each drawing below.
DRAWINGS: tuple[tuple[str, str, int, int, float], ...] = (('STAR_LARGE', 'symbol', 12, 11, 0.3), ('STAR_SMALL', 'symbol', 8, 7, 0.22), ('WORDMARK_LARGE', 'wordmark', 44, 7, 0.5), ('WORDMARK_SMALL', 'wordmark', 30, 5, 0.5))

STAR_LARGE: tuple[str, ...] = (
    '     ▟▌',
    '     █▌',
    '     █▌',
    '  █▄ ▜▌▗▟█',
    '  ▜██▞▚█▛▘',
    '    ▜  ▙',
    '  ▗▟█▚▞██▙',
    '  █▛▘▐▙ ▀█',
    '     ▐█',
    '     ▐▀',
)

STAR_SMALL: tuple[str, ...] = (
    '   ▟▌',
    '   ▐▌',
    ' █▙▟▙█▛',
    '  ▜▌▐▙',
    ' ▟█▜▛▜█',
    '   ▐▌',
    '   ▝',
)

WORDMARK_LARGE: tuple[str, ...] = (
    '███▙▖  ▄██▙▖  ▙      ▗▙   ▐███▄  ▐▌  ▟██▙',
    '█▀▀▀█ ▗▛▘ ▝█  █      ██▖  ▐▛▀▀▜▌ ▐▌ ▐▛  ▜▌',
    '█   █ ▟▌   ▜▌ █     ▗▛▐▌  ▐▌  ▐▌ ▐▌ ▐▙▖',
    '█▄▄▟▛ █▌   ▐▌ █     ▟▌ █  ▐▙▄▄█▘ ▐▌  ▀██▙▖',
    '█▀▀▀  ▜▌   ▟▌ █     ████▖ ▐▛▀▜▌  ▐▌     ▜▙',
    '█     ▝▙▖ ▗█  █▄▄▄▖▐▛  ▐▙ ▐▌  █▖ ▐▌ ▐▙  ▐▛',
    '█      ▀██▛▘  ███▛▘▐▘   ▜ ▐▌  ▝▌ ▐▌  ▜██▛▘',
)

WORDMARK_SMALL: tuple[str, ...] = (
    '██▙▖▗▟█▙ ▐    ▗▌  ██▙▖ ▌ ▟▀▙',
    '▌ ▝▌▐▘ ▐▌▐    ▟▜  █  ▌ ▌ ▙ ▝▘',
    '▙▄▟▘█  ▐▌▐    ▌▐▖ █▄▟▘ ▌ ▀█▙',
    '▛   ▐▖ ▐▌▐   ▐▀▀▙ █ ▜  ▌ ▖ ▐▌',
    '▌   ▝▜█▛ ▐██▘▛  ▜ ▛ ▝▌ ▌ ▜▄█▘',
)

# The site's colour tokens on its porcelain pages (light).
LIGHT: dict[str, str] = {
    'arsenic': '#849183',
    'blue': '#346b63',
    'brass': '#dce8ca',
    'carbon': '#142f27',
    'cloud': '#31483d',
    'context': '#77603e',
    'flag': '#9c432e',
    'graphite': '#667467',
    'ink': '#20382e',
    'line': '#d9e1d6',
    'navy': '#f7f8f3',
    'navy-1': '#edf1e9',
    'navy-2': '#ffffff',
    'navy-3': '#e1e8dd',
    'ok': '#326953',
    'paper': '#f7f8f3',
    'phantom': '#edf1e9',
    'pink': '#8a643b',
    'smoke': '#415549',
    'space': '#596959',
    'steel': '#536457',
    'violet': '#2c614b',
}

# The same tokens on its dark surfaces: code windows and the review panel.
DARK: dict[str, str] = {
    'arsenic': '#849183',
    'blue': '#346b63',
    'brass': '#dce8ca',
    'carbon': '#142f27',
    'cloud': '#e7eee0',
    'context': '#e1d7b8',
    'flag': '#eeac92',
    'graphite': '#a3b9a2',
    'ink': '#f7f8f3',
    'line': '#3c5947',
    'navy': '#142f27',
    'navy-1': '#1c382e',
    'navy-2': '#234236',
    'navy-3': '#345547',
    'ok': '#b5dcca',
    'paper': '#f7f8f3',
    'phantom': '#edf1e9',
    'pink': '#8a643b',
    'smoke': '#d2decd',
    'space': '#a7bda6',
    'steel': '#becfbc',
    'violet': '#d3e5b6',
}

# The polaris-north code colours (used on dark surfaces).
CODE: dict[str, str] = {
    'comment': '#a4ad98',
    'escape': '#eeac92',
    'foreground': '#e8e6db',
    'function': '#e9d6ad',
    'keyword': '#d7b75d',
    'number': '#eeac92',
    'parameter': '#f3f0e8',
    'property': '#d7b75d',
    'punctuation': '#aeb69e',
    'string': '#c4d3ae',
    'type': '#d1d9bd',
}
